services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
  
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"

