FROM python:3.13.2-slim-bookworm
WORKDIR /app
RUN apt update && apt install -y nginx && rm -rf /var/lib/apt/lists/*
COPY . ./
RUN pip install --no-cache -r requirements.txt
ENV PYTHONDONTWRITEBYTECODE=1
RUN python manage.py collectstatic --noinput
COPY nginx.backend.conf /etc/nginx/nginx.conf
CMD nginx -g 'daemon on;' && gunicorn --bind 0.0.0.0:8001 core.wsgi

