FROM python:3.13.2-slim-bookworm
WORKDIR /app
COPY . ./
RUN pip install --no-cache -r requirements.txt
ENV PYTHONDONTWRITEBYTECODE=1
RUN python manage.py collectstatic --noinput
COPY nginx.backend.conf /etc/nginx/nginx.conf
CMD ["gunicorn", "--bind", ":8000", "core.wsgi"]

