FROM node:23-bookworm-slim AS build
WORKDIR /app
COPY ./frontend/package*.json ./
RUN npm install
COPY ./frontend .
RUN npm run build

FROM nginx AS prod
RUN mkdir /app
COPY --from=build /app/dist /app
COPY nginx.frontend.conf /etc/nginx/nginx.conf
